# Generated by Django 5.0 on 2024-02-01 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="datumRodj",
        ),
        migrations.RemoveField(
            model_name="student",
            name="maturaOc",
        ),
        migrations.RemoveField(
            model_name="student",
            name="mjestoRodj",
        ),
        migrations.RemoveField(
            model_name="student",
            name="molbaUpis",
        ),
    ]
