# Generated by Django 5.0 on 2024-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "university",
            "0002_remove_student_datumrodj_remove_student_maturaoc_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
