# Generated by Django 5.0 on 2024-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0003_fieldofstudy"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldofstudy",
            name="quote",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="student",
            name="datumRodj",
            field=models.DateField(default="2001-07-30"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="doc",
            field=models.FileField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="maturaOc",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="mjestoRodj",
            field=models.CharField(default="Zenica", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="molba",
            field=models.CharField(default="Idemo laga", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="description",
            field=models.TextField(default="Smijer obrazovanja"),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="name",
            field=models.CharField(default="Tehnicki", max_length=100),
        ),
    ]
