# Generated by Django 5.0 on 2024-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "university",
            "0004_fieldofstudy_quote_student_datumrodj_student_doc_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="FieldOfStudy",
        ),
        migrations.RemoveField(
            model_name="student",
            name="smijerOdab",
        ),
        migrations.AddField(
            model_name="student",
            name="smijer",
            field=models.CharField(
                choices=[
                    ("Informatički", "Informatički"),
                    ("Tehnički", "Tehnički"),
                    ("Matematički", "Matematički"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
