# Generated by Django 5.0 on 2024-02-03 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0005_delete_fieldofstudy_remove_student_smijerodab_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="number",
            new_name="broj",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="datumRodj",
            new_name="datum",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="fName",
            new_name="ime",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="mjestoRodj",
            new_name="mjesto",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="maturaOc",
            new_name="ocijena_mature",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="lName",
            new_name="prezime",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="prosjekOc",
            new_name="prosjek",
        ),
    ]
