# Generated by Django 5.0 on 2024-02-03 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0006_rename_number_student_broj_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="doc",
        ),
    ]
