# Generated by Django 5.0 on 2024-02-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0007_remove_student_doc"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("student_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="smijer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="university.fieldofstudy",
            ),
        ),
    ]
