# Generated by Django 5.0 on 2024-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0008_fieldofstudy_alter_student_smijer"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldofstudy",
            name="quota",
            field=models.IntegerField(default=0),
        ),
    ]
