# Generated by Django 5.0 on 2024-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0009_fieldofstudy_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="doc",
            field=models.FileField(default=0, upload_to=""),
            preserve_default=False,
        ),
    ]
