# Generated by Django 5.0 on 2024-02-04 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0010_student_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="doc",
        ),
    ]
