# Generated by Django 5.0 on 2024-02-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0011_remove_student_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="doc",
            field=models.FileField(blank=True, null=True, upload_to="pdf_documents/"),
        ),
    ]
